server:
  port: ${SERVER_PORT:8090}

app:
  subscription-service:
    url: ${SERVICE_URL:http://localhost:8090}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/subscribedb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          multiplier: 2
          max-retries: 5

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0